[package]
name = "swaybar-proc-graph"
version = "0.1.0"
authors = ["vjoki"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
anyhow = "1"
argh = "0.1"
nvml-wrapper = { version = "0.8", optional = true }

[features]
default = ["nvidia"]
nvidia = ["dep:nvml-wrapper"]
