[workspace]
resolver = "2"
members = [
   "sway-focus-switcheroo",
   "sway-window-nav",
   "swaybar-proc-graph",
]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
